spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chongya?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

server:
  port: 8080
  servlet:
    context-path: /dev-api/v1

mybatis:
  configuration:
    map-underscore-to-camel-case: true

